# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
    - name: Upload artifacts to Github Actions
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: build/libs
    - name: Clean remove old jars
      run: rm ./build/*.jar || true
    - name: Rename files
      run: |
        cd build/libs
        mv *sources-dev.jar ../iris-fabric-starline-sources-dev.jar
        mv *sources.jar ../iris-fabric-starline-sources.jar
        mv *dev.jar ../iris-fabric-starline-dev.jar
        mv *.jar ../iris-fabric-starline.jar
        rm -r ../libs || true
    - name: Save jars to repo
      run: |
        cd build
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add ./*.jar -f || true
        git commit -m "Update jars"
        git push 
